### ISSUE TITLE
1.0.2 pom.xml says 1.0.2-SNAPSHOT

### ISSUE THREAD

**Issue by veselov** [mryan43/jsend-nrdp#3]
I think the released binary should have 1.0.2 version in pom.xml (just like 1.0.1 does).

**Comment by mryan43** [comment]
Fixed in 1.0.3, which should be synced to central in a few minutes, sorry for the inconvenience !

**Comment by veselov** [comment]
Hmm. 1.0.2 published to Central had a correct POM file :) 1.0.2 available for download on GitHub hit '1.0.2-SNAPSHOT' in pom.xml
I see 1.0.3 on Central, and POM file is also OK. But I don't see 1.0.3 available in GitHub releases :)

**Comment by mryan43** [comment]
Fixed, there is not 1.0.2 anymore since 1.0.3 has the same code
